export const MERN_FRONTEND_FETCH_ITEMS 		= 'MERN_FRONTEND_FETCH_ITEMS';
export const MERN_FRONTEND_ADD_ITEM    		= 'MERN_FRONTEND_ADD_ITEM';
export const MERN_FRONTEND_UPDATE_ITEM 		= 'MERN_FRONTEND_UPDATE_ITEM';
export const MERN_FRONTEND_DELETE_ITEM 		= 'MERN_FRONTEND_DELETE_ITEM';
export const MERN_FRONTEND_UPDATE_MESSAGE = 'MERN_FRONTEND_UPDATE_MESSAGE';
export const MERN_FRONTEND_RESET_MESSAGE  = 'MERN_FRONTEND_RESET_MESSAGE';